<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>IRPanoView.Viewer</RootNamespace>
    <AssemblyName>IRPanoView.Viewer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>
</Project>
